# ArgoCD Application: Saleor DEV

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saleor-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kyeol-apps

  source:
    repoURL: https://github.com/jungbin7/kyeol-app-gitops.git
    targetRevision: main
    path: apps/saleor/overlays/dev

  destination:
    name: dev-cluster
    namespace: kyeol

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
